apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat-daemonset
  namespace: debug
spec:
  template:
    metadata:
     labels:
       apps: filebeat-daemonset
    spec:
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      containers:
      - name: filebeat
        imagePullPolicy: Always
        image: gcr.io/kube-simulation/filebeat:0.5
        terminationMessagePath: /dev/termination-log
        env:
        - name: LOGSTASH_HOST
          value: "'logstash-buffer-logging.debug.svc.cluster.local:11000'"
        - name: LOG_LEVEL
          value: info
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
