apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana-logging
        image: gcr.io/google_containers/kibana:1.3
        ports:
          - name: ui
            containerPort: 5601
            protocol: TCP
        env:
          - name: ELASTIC_SEARCH_URL
            value: https://elasticsearch-logging:9200
        volumeMounts:
          - name: es-peristent-storage
            mountPath: /data
            