apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-filter-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: logstash-filter
    spec:
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      containers:
      - name: logstash
        imagePullPolicy: Always
        image: gcr.io/kube-simulation/logstash-filter:0.1
        terminationMessagePath: /dev/termination-log
        ports:
        - containerPort: 11000
          name: log
          protocol: TCP
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers

