apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-deployments
  namespace: kube-system
spec:
  replicas: 3
  template:
    metadata:
      labels: 
        app: dummy
    spec:
      containers:
      - name: dummy
        image: ubuntu:14.04
        args: [bash, -c, 'for ((i = 0; "$i" -lt "15121995"; i++)); do echo "$i: $(date)"; sleep 1; done']
      volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
