apiVersion: v1
kind: Service
metadata:
  name: rails-log-logging
  labels:
    app: rails-log-logging
spec:
  ports:
  - port: 3366
    protocol: TCP
    targetPort: rlog
  selector:
    app: rails-log
  type: LoadBalancer
