apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: rails-log-deployment
  namespace: kube-system
spec: 
  replicas: 2
  template:
    metadata:
      labels:
        app: rails-log
    spec:
      containers:
      - image: gcr.io/kube-simulation/rails-log:0.1
        name: rails-log
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        ports:
        - containerPort: 3366
          name: rlog
          protocol: TCP
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
