apiVersion: v1
kind: Service
metadata:
  name: nodesheen-logging
  labels:
    app: nodesheen-logging
spec:
  ports:
  - port: 4567
    protocol: TCP
    targetPort: sin
  selector:
    app: nodesheen
  type: LoadBalancer
