apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: nodesheen-deployment
spec: 
  replicas: 2
  template:
    metadata:
      labels:
        app: nodesheen
    spec:
      containers:
      - image: rvu95/nodesheen:0.1
        name: nodesheen
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        ports:
        - containerPort: 15120
          name: nod
          protocol: TCP
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
