apiVersion: v1
kind: Service
metadata:
  name: nodesheen-logging
  labels:
    app: nodesheen-logging
spec:
  ports:
  - port: 15120
    protocol: TCP
    targetPort: nod
  selector:
    app: nodesheen
  type: LoadBalancer
