apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: sinatra-deployment
  namespace: kube-system
spec: 
  replicas: 2
  template:
    metadata:
      labels:
        app: sinatra
    spec:
      containers:
      - image: gcr.io/kube-simulation/sinatra:0.1
        name: sinatra
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        ports:
        - containerPort: 4567
          name: sin
          protocol: TCP
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
