# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae0a69f4bd7fdb317d5a9f8221f9250c5f68bc6421a35dcf0a91f76b947450a7d19608f2d1874aae7b1e366668e94e29a460b3541a4c28fa600676bdb569c175

test:
  secret_key_base: d8070ca32f01b24fc5edc55857a8e4be56c5c3a19988e4bd3a5481b09079fb8673dc563461269fe11e119024f9a912232f2921a7deaae33b5b71c5e89b2781e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
