apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: debug
  labels:
    app: elasticsearch-logging
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    app: elasticsearch
