apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  labels:
    app: kibana-logging
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    app: kibana
  type: LoadBalancer
