apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-deployments
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      containers:
      - image: kibana:4.0
        name: kibana
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging.default.svc.cluster.local:9200"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
