apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: filebeat-deployment
  namespace: kube-system
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        imagePullPolicy: Always
        image: gcr.io/kube-simulation/filebeat-elasticsearch:0.1
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - name: varlog
            mountPath: /var/log
      volumes:
        - name: varlog
          hostpath:
            - path: /var/log
