apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat-daemonset
  namespace: kube-system
spec:
  template:
    metadata:
     labels:
       apps: filebeat-daemonset
    spec:
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      containers:
      - name: filebeat
        imagePullPolicy: Always
        image: gcr.io/kube-simulation/filebeat-elasticsearch:0.1
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
