apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-deployments
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - image: kibana:4.0
        name: kibana
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging.kube-system.svc.cluster.local:9200"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
