apiVersion: v1
kind: Service
metadata:
  name: logstash-logging
  namespace: kube-system
  labels:
    app: logstash-logging
spec:
  ports:
  - port: 11000
    protocol: TCP
    targetPort: log
  selector:
    app: logstash
