apiVersion: v1
kind: Service
metadata:
  name: sinatra-logging
  namespace: kube-system
  labels:
    app: sinatra-logging
spec:
  ports:
  - port: 4567
    protocol: TCP
    targetPort: sin
  selector:
    app: sinatra
  type: LoadBalancer
