apiVersion: v1
kind: Service
metadata:
  name: gosheen-logging
  labels:
    app: gosheen-logging
spec:
  ports:
  - port: 4567
    protocol: TCP
    targetPort: sin
  selector:
    app: gosheen
  type: LoadBalancer
